import type {
  InfusionDefinition,
  ModDefinition,
  QuirkDefinition,
  RarityDefinition,
  SynergyDefinition,
  LootUpgradeDefinition,
  WeaponArchetype,
} from './types';

export const RARITY_TABLE: RarityDefinition[] = [
  { id: 'common', weight: 42, affixes: 1, quirkChance: 0.15 },
  { id: 'uncommon', weight: 28, affixes: 2, quirkChance: 0.2 },
  { id: 'rare', weight: 16, affixes: 3, quirkChance: 0.3 },
  { id: 'epic', weight: 9, affixes: 4, quirkChance: 0.4 },
  { id: 'legendary', weight: 4, affixes: 5, quirkChance: 0.5 },
  { id: 'mythic', weight: 1, affixes: 6, quirkChance: 0.7 },
];

export const WEAPON_ARCHETYPES: WeaponArchetype[] = [
  {
    id: 'slugger',
    name: 'Slugger',
    weight: 10,
    tags: ['kinetic', 'precision', 'rail', 'long'],
    stats: {
      damage: 34,
      cooldownMs: 680,
      projectileCount: 1,
      spread: 1.5,
      range: 900,
      critChance: 0.18,
      critMultiplier: 2.2,
      magazine: 6,
      reloadMs: 1600,
    },
    description: 'Heavy single-shot rifle with long range and high crits.',
    modBiasTags: ['precision', 'crit', 'rail'],
  },
  {
    id: 'sprayer',
    name: 'Sprayer',
    weight: 12,
    tags: ['kinetic', 'spray', 'close', 'light'],
    stats: {
      damage: 6,
      cooldownMs: 90,
      projectileCount: 1,
      spread: 10,
      range: 420,
      critChance: 0.05,
      critMultiplier: 1.4,
      magazine: 50,
      reloadMs: 1300,
    },
    description: 'High fire rate scattergun that floods the air with lead.',
    modBiasTags: ['spray', 'reload', 'ammo'],
  },
  {
    id: 'scattershot',
    name: 'Scattershot',
    weight: 11,
    tags: ['kinetic', 'scatter', 'close', 'burst'],
    stats: {
      damage: 5,
      cooldownMs: 820,
      projectileCount: 9,
      spread: 14,
      range: 320,
      critChance: 0.08,
      critMultiplier: 1.6,
      magazine: 4,
      reloadMs: 1800,
      burstCount: 1,
    },
    description: 'Shotgun pattern weapon with devastating point-blank bursts.',
    modBiasTags: ['scatter', 'close', 'aoe'],
  },
  {
    id: 'lancer',
    name: 'Lancer',
    weight: 10,
    tags: ['energy', 'beam', 'long', 'precision'],
    stats: {
      damage: 16,
      cooldownMs: 240,
      projectileCount: 1,
      spread: 2,
      range: 820,
      critChance: 0.12,
      critMultiplier: 1.9,
      magazine: 24,
      reloadMs: 1500,
    },
    description: 'Sustained beam emitter that rewards accuracy.',
    modBiasTags: ['beam', 'precision', 'crit'],
  },
  {
    id: 'storm',
    name: 'Storm Coil',
    weight: 10,
    tags: ['energy', 'shock', 'chain', 'mid'],
    stats: {
      damage: 12,
      cooldownMs: 180,
      projectileCount: 1,
      spread: 5,
      range: 650,
      critChance: 0.1,
      critMultiplier: 1.7,
      magazine: 30,
      reloadMs: 1400,
    },
    description: 'Electrical projector that jumps between clustered targets.',
    modBiasTags: ['chain', 'shock', 'status'],
  },
  {
    id: 'pyre',
    name: 'Pyre',
    weight: 9,
    tags: ['energy', 'burn', 'dot', 'aoe', 'mid'],
    stats: {
      damage: 10,
      cooldownMs: 260,
      projectileCount: 1,
      spread: 7,
      range: 600,
      critChance: 0.06,
      critMultiplier: 1.5,
      magazine: 18,
      reloadMs: 1600,
    },
    description: 'Incendiary launcher that blankets zones in burning plasma.',
    modBiasTags: ['burn', 'dot', 'aoe'],
  },
  {
    id: 'thumper',
    name: 'Thumper',
    weight: 8,
    tags: ['explosive', 'launcher', 'aoe', 'heavy', 'mid'],
    stats: {
      damage: 26,
      cooldownMs: 920,
      projectileCount: 1,
      spread: 6,
      range: 620,
      critChance: 0.04,
      critMultiplier: 1.5,
      magazine: 3,
      reloadMs: 1900,
    },
    description: 'Grenade launcher with massive blast radius.',
    modBiasTags: ['explosive', 'aoe', 'volatile'],
  },
  {
    id: 'needle',
    name: 'Needle',
    weight: 10,
    tags: ['kinetic', 'bleed', 'pierce', 'precision', 'mid'],
    stats: {
      damage: 18,
      cooldownMs: 320,
      projectileCount: 1,
      spread: 2.5,
      range: 720,
      critChance: 0.16,
      critMultiplier: 2.0,
      magazine: 14,
      reloadMs: 1200,
    },
    description: 'Armor-piercing spikes that stack bleeding wounds.',
    modBiasTags: ['bleed', 'pierce', 'crit'],
  },
  {
    id: 'orbiter',
    name: 'Orbiter',
    weight: 7,
    tags: ['plasma', 'orb', 'orbit', 'mid'],
    stats: {
      damage: 9,
      cooldownMs: 200,
      projectileCount: 1,
      spread: 4,
      range: 560,
      critChance: 0.08,
      critMultiplier: 1.6,
      magazine: 28,
      reloadMs: 1500,
    },
    description: 'Slow plasma orbs that circle and detonate on contact.',
    modBiasTags: ['orb', 'orbit', 'aoe'],
  },
  {
    id: 'hive',
    name: 'Hive',
    weight: 6,
    tags: ['summon', 'drone', 'support', 'mid'],
    stats: {
      damage: 7,
      cooldownMs: 420,
      projectileCount: 1,
      spread: 6,
      range: 520,
      critChance: 0.05,
      critMultiplier: 1.4,
      magazine: 10,
      reloadMs: 1800,
    },
    description: 'Deploys autonomous drones that harass targets.',
    modBiasTags: ['summon', 'drone', 'support'],
  },
  {
    id: 'glacier',
    name: 'Glacier',
    weight: 7,
    tags: ['cryo', 'shatter', 'aoe', 'mid'],
    stats: {
      damage: 14,
      cooldownMs: 360,
      projectileCount: 1,
      spread: 6,
      range: 640,
      critChance: 0.1,
      critMultiplier: 1.7,
      magazine: 12,
      reloadMs: 1500,
    },
    description: 'Cryo cannon that freezes and fractures targets.',
    modBiasTags: ['cryo', 'shatter', 'status'],
  },
  {
    id: 'ripper',
    name: 'Ripper',
    weight: 10,
    tags: ['kinetic', 'ricochet', 'burst', 'mid'],
    stats: {
      damage: 11,
      cooldownMs: 210,
      projectileCount: 1,
      spread: 4,
      range: 620,
      critChance: 0.12,
      critMultiplier: 1.8,
      magazine: 30,
      reloadMs: 1400,
      burstCount: 3,
    },
    description: 'Burst rifle with ricochet-capable rounds.',
    modBiasTags: ['ricochet', 'burst', 'crit'],
  },
];

export const INFUSIONS: InfusionDefinition[] = [
  {
    id: 'pyro',
    name: 'Pyro',
    weight: 8,
    tags: ['burn', 'dot', 'status'],
    modifiers: {
      add: { damage: 2 },
      mult: { cooldownMs: 1.05 },
    },
    description: 'Adds burning damage over time.',
    namePrefix: 'Pyro',
  },
  {
    id: 'cryo',
    name: 'Cryo',
    weight: 7,
    tags: ['cryo', 'shatter', 'status'],
    modifiers: {
      add: { damage: 1 },
      mult: { cooldownMs: 1.02 },
    },
    description: 'Slows targets and enables shatter bursts.',
    namePrefix: 'Cryo',
  },
  {
    id: 'shock',
    name: 'Shock',
    weight: 7,
    tags: ['shock', 'chain', 'status'],
    modifiers: {
      add: { critChance: 0.03 },
      mult: { cooldownMs: 1.08 },
    },
    description: 'Adds shock jumps between targets.',
    namePrefix: 'Shock',
  },
  {
    id: 'corrosive',
    name: 'Corrosive',
    weight: 6,
    tags: ['corrosive', 'dot', 'status'],
    modifiers: {
      add: { damage: 1 },
      mult: { range: 0.95 },
    },
    description: 'Erodes armor and stacks damage.',
    namePrefix: 'Corrosive',
  },
  {
    id: 'plasma',
    name: 'Plasma',
    weight: 6,
    tags: ['plasma', 'orb', 'aoe'],
    modifiers: {
      add: { damage: 2 },
      mult: { spread: 1.1 },
    },
    description: 'Converts payloads into volatile plasma.',
    namePrefix: 'Plasma',
  },
  {
    id: 'volatile',
    name: 'Volatile',
    weight: 5,
    tags: ['volatile', 'aoe', 'explosive'],
    modifiers: {
      add: { damage: 3 },
      mult: { cooldownMs: 1.12 },
    },
    description: 'Volatile rounds trigger small explosions.',
    namePrefix: 'Volatile',
  },
  {
    id: 'magnet',
    name: 'Magnet',
    weight: 4,
    tags: ['magnet', 'ricochet', 'utility'],
    modifiers: {
      add: { range: 40 },
      mult: { spread: 0.9 },
    },
    description: 'Projectiles curve toward targets.',
    namePrefix: 'Magnet',
  },
  {
    id: 'overcharge',
    name: 'Overcharge',
    weight: 3,
    tags: ['overheat', 'flow', 'status'],
    modifiers: {
      add: { damage: 4 },
      mult: { cooldownMs: 1.18 },
    },
    description: 'Huge damage spikes with heat build-up.',
    namePrefix: 'Overcharged',
  },
];

export const MOD_DEFINITIONS: ModDefinition[] = [
  {
    id: 'barrel_smooth',
    name: 'Smooth Barrel',
    group: 'barrel',
    weight: 12,
    tags: ['precision'],
    modifiers: { mult: { spread: 0.8 } },
    description: 'Tightens projectile spread.',
    namePrefix: 'Smooth',
  },
  {
    id: 'barrel_flared',
    name: 'Flared Barrel',
    group: 'barrel',
    weight: 10,
    tags: ['scatter', 'aoe'],
    modifiers: { mult: { spread: 1.25, projectileCount: 1.15 } },
    description: 'Wider arc with extra pellets.',
    namePrefix: 'Flared',
    requiresTags: ['scatter'],
  },
  {
    id: 'barrel_vented',
    name: 'Vented Barrel',
    group: 'barrel',
    weight: 9,
    tags: ['overheat', 'flow'],
    modifiers: { mult: { cooldownMs: 0.9 } },
    description: 'Bleeds heat to boost fire rate.',
    namePrefix: 'Vented',
  },
  {
    id: 'barrel_focused',
    name: 'Focused Barrel',
    group: 'barrel',
    weight: 8,
    tags: ['beam', 'precision'],
    modifiers: { add: { range: 80 }, mult: { spread: 0.75 } },
    description: 'Concentrated beam for long-range hits.',
    requiresTags: ['beam'],
  },
  {
    id: 'receiver_overclock',
    name: 'Overclocked Receiver',
    group: 'receiver',
    weight: 8,
    tags: ['overheat', 'spike'],
    modifiers: { mult: { cooldownMs: 0.82, damage: 1.08 } },
    description: 'Faster cycling at the cost of heat.',
    namePrefix: 'Overclocked',
  },
  {
    id: 'receiver_reinforced',
    name: 'Reinforced Receiver',
    group: 'receiver',
    weight: 8,
    tags: ['heavy', 'stability'],
    modifiers: { add: { damage: 3 }, mult: { cooldownMs: 1.1 } },
    description: 'Heavier frame with higher impact.',
    namePrefix: 'Reinforced',
  },
  {
    id: 'receiver_honed',
    name: 'Honed Receiver',
    group: 'receiver',
    weight: 8,
    tags: ['precision', 'crit'],
    modifiers: { add: { critChance: 0.06 }, mult: { damage: 1.04 } },
    description: 'Improved tolerances for critical hits.',
    namePrefix: 'Honed',
  },
  {
    id: 'chip_chain',
    name: 'Chain Chip',
    group: 'chip',
    weight: 7,
    tags: ['chain', 'shock'],
    modifiers: { mult: { damage: 0.96 }, add: { range: 30 } },
    description: 'Adds chain lightning arcs.',
    nameSuffix: 'of Storms',
  },
  {
    id: 'chip_shatter',
    name: 'Shatter Chip',
    group: 'chip',
    weight: 7,
    tags: ['cryo', 'shatter'],
    modifiers: { add: { damage: 2 }, mult: { cooldownMs: 1.05 } },
    description: 'Builds shatter stacks on frozen targets.',
    nameSuffix: 'of Fractures',
  },
  {
    id: 'chip_bleed',
    name: 'Bleed Chip',
    group: 'chip',
    weight: 7,
    tags: ['bleed', 'dot'],
    modifiers: { add: { damage: 1 }, mult: { cooldownMs: 1.03 } },
    description: 'Inflicts bleeding wounds that stack.',
    nameSuffix: 'of Thorns',
  },
  {
    id: 'chip_corrosive',
    name: 'Corrosive Chip',
    group: 'chip',
    weight: 6,
    tags: ['corrosive', 'dot'],
    modifiers: { add: { damage: 1 }, mult: { range: 0.9 } },
    description: 'Acidic rounds strip armor.',
    nameSuffix: 'of Dissolution',
  },
  {
    id: 'chip_pulse',
    name: 'Pulse Chip',
    group: 'chip',
    weight: 6,
    tags: ['pulse', 'aoe'],
    modifiers: { add: { damage: 2 }, mult: { cooldownMs: 1.07 } },
    description: 'Adds pulsing shockwaves.',
    nameSuffix: 'of Pulses',
  },
  {
    id: 'mag_oversized',
    name: 'Oversized Mag',
    group: 'mag',
    weight: 10,
    tags: ['ammo'],
    modifiers: { add: { magazine: 8 }, mult: { reloadMs: 1.1 } },
    description: 'More shots before reloading.',
  },
  {
    id: 'mag_quickload',
    name: 'Quickload Mag',
    group: 'mag',
    weight: 9,
    tags: ['reload', 'flow'],
    modifiers: { mult: { reloadMs: 0.75 } },
    description: 'Faster reload cycles.',
  },
  {
    id: 'mag_pressurized',
    name: 'Pressurized Mag',
    group: 'mag',
    weight: 7,
    tags: ['burst', 'spike'],
    modifiers: { add: { burstCount: 1 }, mult: { cooldownMs: 1.08 } },
    description: 'Adds extra burst shot.',
    requiresTags: ['burst'],
  },
  {
    id: 'lens_rangefinder',
    name: 'Rangefinder Lens',
    group: 'lens',
    weight: 8,
    tags: ['precision', 'long'],
    modifiers: { add: { range: 120 }, mult: { spread: 0.9 } },
    description: 'Improves long-range accuracy.',
  },
  {
    id: 'lens_diffuser',
    name: 'Diffuser Lens',
    group: 'lens',
    weight: 7,
    tags: ['aoe', 'scatter'],
    modifiers: { mult: { spread: 1.2, projectileCount: 1.1 } },
    description: 'Creates a wider impact zone.',
  },
  {
    id: 'core_critical',
    name: 'Critical Core',
    group: 'core',
    weight: 6,
    tags: ['crit', 'spike'],
    modifiers: { add: { critChance: 0.08, critMultiplier: 0.3 } },
    description: 'Boosts critical hit damage.',
    nameSuffix: 'of Precision',
  },
  {
    id: 'core_rapid',
    name: 'Rapid Core',
    group: 'core',
    weight: 6,
    tags: ['light', 'flow'],
    modifiers: { mult: { cooldownMs: 0.85, damage: 0.95 } },
    description: 'Higher rate of fire at lower impact.',
    nameSuffix: 'of Velocity',
  },
  {
    id: 'core_payload',
    name: 'Payload Core',
    group: 'core',
    weight: 5,
    tags: ['explosive', 'volatile', 'aoe'],
    modifiers: { add: { damage: 4 }, mult: { cooldownMs: 1.12 } },
    description: 'Adds explosive payloads.',
    requiresTags: ['explosive'],
    nameSuffix: 'of Impact',
  },
  {
    id: 'core_beam',
    name: 'Beam Core',
    group: 'core',
    weight: 5,
    tags: ['beam', 'charge'],
    modifiers: { add: { range: 60 }, mult: { cooldownMs: 1.05 } },
    description: 'Stabilized beam focusing crystal.',
    requiresTags: ['beam'],
  },
  {
    id: 'stock_balance',
    name: 'Balanced Stock',
    group: 'stock',
    weight: 8,
    tags: ['utility'],
    modifiers: { mult: { spread: 0.9, cooldownMs: 0.97 } },
    description: 'Balanced handling profile.',
  },
  {
    id: 'stock_recoil',
    name: 'Recoil Dampener',
    group: 'stock',
    weight: 7,
    tags: ['precision'],
    modifiers: { mult: { spread: 0.85 } },
    description: 'Tames recoil for better accuracy.',
  },
  {
    id: 'stock_assault',
    name: 'Assault Stock',
    group: 'stock',
    weight: 7,
    tags: ['mobile', 'light'],
    modifiers: { mult: { cooldownMs: 0.95 } },
    description: 'Improves mobility while firing.',
  },
  {
    id: 'payload_splitter',
    name: 'Splitter Payload',
    group: 'payload',
    weight: 6,
    tags: ['scatter', 'aoe'],
    modifiers: { add: { projectileCount: 2 }, mult: { damage: 0.9 } },
    description: 'Splits projectiles into extra shards.',
  },
  {
    id: 'payload_piercer',
    name: 'Piercer Payload',
    group: 'payload',
    weight: 6,
    tags: ['pierce'],
    modifiers: { add: { range: 40 }, mult: { damage: 1.04 } },
    description: 'Shots pierce through targets.',
  },
  {
    id: 'payload_ricochet',
    name: 'Ricochet Payload',
    group: 'payload',
    weight: 6,
    tags: ['ricochet', 'magnet'],
    modifiers: { mult: { damage: 0.97 }, add: { range: 20 } },
    description: 'Rounds bounce between enemies.',
  },
  {
    id: 'catalyst_orbit',
    name: 'Orbit Catalyst',
    group: 'catalyst',
    weight: 5,
    tags: ['orbit', 'orb', 'aoe'],
    modifiers: { mult: { cooldownMs: 1.08 }, add: { damage: 2 } },
    description: 'Creates orbiting orbs around targets.',
  },
  {
    id: 'catalyst_drone',
    name: 'Drone Catalyst',
    group: 'catalyst',
    weight: 5,
    tags: ['drone', 'summon', 'support'],
    modifiers: { add: { damage: 1 }, mult: { cooldownMs: 1.05 } },
    description: 'Adds autonomous drone spawns.',
  },
  {
    id: 'catalyst_trap',
    name: 'Trap Catalyst',
    group: 'catalyst',
    weight: 5,
    tags: ['trap', 'aoe'],
    modifiers: { add: { damage: 2 }, mult: { cooldownMs: 1.12 } },
    description: 'Shots leave lingering traps.',
  },
  {
    id: 'catalyst_shield',
    name: 'Barrier Catalyst',
    group: 'catalyst',
    weight: 4,
    tags: ['barrier', 'support', 'shield'],
    modifiers: { mult: { cooldownMs: 1.06 }, add: { range: 30 } },
    description: 'Projects a temporary barrier on hit.',
  },
  {
    id: 'module_scope',
    name: 'Holo Scope',
    group: 'module',
    weight: 6,
    tags: ['precision', 'long'],
    modifiers: { add: { critChance: 0.04 }, mult: { spread: 0.9 } },
    description: 'Improves long-range targeting.',
  },
  {
    id: 'module_overseer',
    name: 'Overseer Module',
    group: 'module',
    weight: 5,
    tags: ['support', 'utility'],
    modifiers: { add: { range: 40 }, mult: { cooldownMs: 0.98 } },
    description: 'Improves battlefield visibility and tracking.',
  },
  {
    id: 'module_amp',
    name: 'Amp Module',
    group: 'module',
    weight: 6,
    tags: ['energy', 'flow'],
    modifiers: { mult: { damage: 1.07 } },
    description: 'Energized output amplifier.',
  },
  {
    id: 'module_stabilizer',
    name: 'Gyro Stabilizer',
    group: 'module',
    weight: 6,
    tags: ['precision', 'stationary'],
    modifiers: { mult: { spread: 0.8 }, add: { range: 50 } },
    description: 'Stabilizes aim while stationary.',
  },
  {
    id: 'chip_spike',
    name: 'Spike Chip',
    group: 'chip',
    weight: 5,
    tags: ['spike', 'crit'],
    modifiers: { add: { critMultiplier: 0.4 }, mult: { cooldownMs: 1.06 } },
    description: 'Massive crit spikes on bursts.',
    nameSuffix: 'of Spikes',
  },
  {
    id: 'chip_flow',
    name: 'Flow Chip',
    group: 'chip',
    weight: 6,
    tags: ['flow', 'reload'],
    modifiers: { mult: { reloadMs: 0.85, cooldownMs: 0.96 } },
    description: 'Smooth reloads and sustained fire.',
    nameSuffix: 'of Flow',
  },
  {
    id: 'chip_echo',
    name: 'Echo Chip',
    group: 'chip',
    weight: 5,
    tags: ['echo', 'pulse'],
    modifiers: { add: { damage: 1 }, mult: { cooldownMs: 1.02 } },
    description: 'Echo pulses repeat after impact.',
    nameSuffix: 'of Echoes',
  },
  {
    id: 'payload_surge',
    name: 'Surge Payload',
    group: 'payload',
    weight: 5,
    tags: ['shock', 'pulse'],
    modifiers: { add: { damage: 2 }, mult: { cooldownMs: 1.08 } },
    description: 'Emits shock pulses on hit.',
  },
  {
    id: 'payload_cripple',
    name: 'Crippling Payload',
    group: 'payload',
    weight: 5,
    tags: ['status', 'slow'],
    modifiers: { mult: { damage: 0.96 }, add: { range: 20 } },
    description: 'Shots hinder enemy movement.',
  },
  {
    id: 'catalyst_chain',
    name: 'Arc Catalyst',
    group: 'catalyst',
    weight: 4,
    tags: ['chain', 'shock'],
    modifiers: { mult: { cooldownMs: 1.1 }, add: { damage: 2 } },
    description: 'Adds heavy chain arcs.',
  },
  {
    id: 'core_pierce',
    name: 'Pierce Core',
    group: 'core',
    weight: 5,
    tags: ['pierce', 'precision'],
    modifiers: { mult: { damage: 1.05 }, add: { range: 40 } },
    description: 'Improves penetration and range.',
  },
  {
    id: 'core_scatter',
    name: 'Scatter Core',
    group: 'core',
    weight: 5,
    tags: ['scatter', 'spray'],
    modifiers: { mult: { projectileCount: 1.15 }, add: { spread: 2 } },
    description: 'Adds extra pellets and spray.',
  },
  {
    id: 'core_heatsink',
    name: 'Heat Sink Core',
    group: 'core',
    weight: 5,
    tags: ['overheat', 'flow'],
    modifiers: { mult: { cooldownMs: 0.92 }, add: { magazine: 4 } },
    description: 'Improves heat dissipation.',
  },
  {
    id: 'module_overdrive',
    name: 'Overdrive Module',
    group: 'module',
    weight: 4,
    tags: ['overheat', 'spike'],
    modifiers: { mult: { damage: 1.1 }, add: { critChance: 0.02 } },
    description: 'Overdrives output with a heat cost.',
  },
];

export const QUIRKS: QuirkDefinition[] = [
  {
    id: 'quirk_glass',
    name: 'Glass Cannon',
    weight: 6,
    tags: ['spike'],
    modifiers: { mult: { damage: 1.18, cooldownMs: 1.08 } },
    description: 'Massive burst damage with slower cycling.',
    namePrefix: 'Glass',
  },
  {
    id: 'quirk_ramp',
    name: 'Ramp Module',
    weight: 6,
    tags: ['stacking', 'flow'],
    modifiers: { mult: { cooldownMs: 0.95 }, add: { damage: 1 } },
    description: 'Stacks power the longer you fire.',
    namePrefix: 'Ramp',
  },
  {
    id: 'quirk_wide',
    name: 'Wide Pattern',
    weight: 5,
    tags: ['scatter', 'aoe'],
    modifiers: { mult: { spread: 1.4, projectileCount: 1.2 } },
    description: 'Wider spread with extra pellets.',
    requiresTags: ['scatter'],
    namePrefix: 'Wide',
  },
  {
    id: 'quirk_tight',
    name: 'Tight Pattern',
    weight: 5,
    tags: ['precision'],
    modifiers: { mult: { spread: 0.7, cooldownMs: 1.05 } },
    description: 'Super tight accuracy at a speed cost.',
    namePrefix: 'Tight',
  },
  {
    id: 'quirk_fume',
    name: 'Fume Trail',
    weight: 4,
    tags: ['dot', 'status'],
    modifiers: { mult: { cooldownMs: 1.06 }, add: { damage: 1 } },
    description: 'Leaves a toxic trail behind shots.',
  },
  {
    id: 'quirk_volatile',
    name: 'Hair Trigger',
    weight: 4,
    tags: ['spike', 'volatile'],
    modifiers: { mult: { cooldownMs: 0.85, damage: 0.92 } },
    description: 'Fast reaction but less stable impact.',
  },
  {
    id: 'quirk_greedy',
    name: 'Greedy Feed',
    weight: 4,
    tags: ['ammo', 'reload'],
    modifiers: { add: { magazine: 6 }, mult: { reloadMs: 1.2 } },
    description: 'Huge magazines but long reloads.',
  },
  {
    id: 'quirk_vortex',
    name: 'Vortex Shot',
    weight: 3,
    tags: ['magnet', 'aoe'],
    modifiers: { mult: { cooldownMs: 1.1 }, add: { range: 50 } },
    description: 'Pulls targets slightly toward impact.',
  },
];

export const UPGRADE_DEFINITIONS: LootUpgradeDefinition[] = [
  {
    id: 'upgrade_targeter',
    name: 'Adaptive Targeter',
    description: 'Crits build faster on the same target.',
    weight: 10,
    tags: ['crit', 'precision'],
  },
  {
    id: 'upgrade_relay',
    name: 'Chain Relay',
    description: 'Chain effects jump one extra target.',
    weight: 8,
    tags: ['chain', 'shock'],
  },
  {
    id: 'upgrade_vents',
    name: 'Heat Vents',
    description: 'Overheat effects recover faster.',
    weight: 9,
    tags: ['overheat', 'flow'],
  },
  {
    id: 'upgrade_quickhands',
    name: 'Quick Hands',
    description: 'Reloading grants a temporary fire rate spike.',
    weight: 9,
    tags: ['reload', 'flow'],
  },
  {
    id: 'upgrade_scatterfield',
    name: 'Scatterfield',
    description: 'Close-range hits spawn extra pellets.',
    weight: 7,
    tags: ['scatter', 'close'],
  },
  {
    id: 'upgrade_cryobank',
    name: 'Cryobank',
    description: 'Cryo damage builds toward a shatter burst.',
    weight: 7,
    tags: ['cryo', 'shatter'],
  },
  {
    id: 'upgrade_biotoxin',
    name: 'Biotoxin',
    description: 'Corrosive stacks spread to nearby enemies.',
    weight: 7,
    tags: ['corrosive', 'dot', 'aoe'],
  },
  {
    id: 'upgrade_arsenal',
    name: 'Expanded Arsenal',
    description: 'Gain an extra mod slot on new weapons.',
    weight: 6,
    tags: ['utility', 'ammo'],
  },
  {
    id: 'upgrade_orbitals',
    name: 'Orbital Buffer',
    description: 'Orbs orbit longer and hit harder.',
    weight: 6,
    tags: ['orb', 'orbit'],
  },
  {
    id: 'upgrade_beamfocus',
    name: 'Beam Focus',
    description: 'Beam weapons gain extra range and crit.',
    weight: 6,
    tags: ['beam', 'precision'],
  },
  {
    id: 'upgrade_surge',
    name: 'Surge Capacitor',
    description: 'Shock effects pulse for bonus damage.',
    weight: 6,
    tags: ['shock', 'pulse'],
  },
  {
    id: 'upgrade_volatile',
    name: 'Volatile Cache',
    description: 'Explosions chain into smaller blasts.',
    weight: 6,
    tags: ['explosive', 'volatile', 'aoe'],
  },
  {
    id: 'upgrade_bleed',
    name: 'Hemorrhage',
    description: 'Bleed stacks boost critical damage.',
    weight: 6,
    tags: ['bleed', 'crit'],
  },
  {
    id: 'upgrade_precision',
    name: 'Ranged Discipline',
    description: 'Long-range kills refund ammo.',
    weight: 6,
    tags: ['long', 'precision', 'ammo'],
  },
  {
    id: 'upgrade_flow',
    name: 'Flow Battery',
    description: 'Sustained firing grants ramping damage.',
    weight: 5,
    tags: ['flow', 'stacking'],
  },
  {
    id: 'upgrade_spike',
    name: 'Spike Timing',
    description: 'Burst fire gains extra crit chance.',
    weight: 5,
    tags: ['burst', 'crit', 'spike'],
  },
  {
    id: 'upgrade_shield',
    name: 'Shield Link',
    description: 'Barrier effects feed shields.',
    weight: 5,
    tags: ['barrier', 'shield', 'support'],
  },
  {
    id: 'upgrade_drones',
    name: 'Drone Overwatch',
    description: 'Drones inherit a percentage of weapon mods.',
    weight: 5,
    tags: ['drone', 'summon', 'support'],
  },
  {
    id: 'upgrade_magnet',
    name: 'Magnet Array',
    description: 'Magnet effects pull in projectiles.',
    weight: 5,
    tags: ['magnet', 'utility'],
  },
  {
    id: 'upgrade_barrel',
    name: 'Barrel Mastery',
    description: 'Barrel mods gain a bonus effect.',
    weight: 5,
    tags: ['precision', 'utility'],
  },
  {
    id: 'upgrade_orbit',
    name: 'Orbit Momentum',
    description: 'Orbiting shots gain speed and damage.',
    weight: 5,
    tags: ['orbit', 'orb', 'flow'],
  },
  {
    id: 'upgrade_echo',
    name: 'Echo Protocol',
    description: 'Echo pulses repeat after a short delay.',
    weight: 5,
    tags: ['echo', 'pulse'],
  },
  {
    id: 'upgrade_drill',
    name: 'Drill Rounds',
    description: 'Piercing shots deal extra damage.',
    weight: 5,
    tags: ['pierce', 'precision'],
  },
  {
    id: 'upgrade_storm',
    name: 'Stormfront',
    description: 'Chain lightning doubles on elite targets.',
    weight: 4,
    tags: ['chain', 'shock', 'spike'],
  },
  {
    id: 'upgrade_chill',
    name: 'Deep Freeze',
    description: 'Frozen targets explode on death.',
    weight: 4,
    tags: ['cryo', 'aoe', 'shatter'],
  },
  {
    id: 'upgrade_molten',
    name: 'Molten Core',
    description: 'Burn effects increase explosive radius.',
    weight: 4,
    tags: ['burn', 'aoe', 'explosive'],
  },
  {
    id: 'upgrade_support',
    name: 'Field Surgeon',
    description: 'Support actions heal and boost fire rate.',
    weight: 4,
    tags: ['support', 'healing'],
  },
  {
    id: 'upgrade_trapline',
    name: 'Trapline',
    description: 'Traps chain into nearby traps.',
    weight: 4,
    tags: ['trap', 'aoe'],
  },
  {
    id: 'upgrade_harmony',
    name: 'Crew Harmony',
    description: 'Mixing tags grants bonus damage.',
    weight: 4,
    tags: ['utility', 'support'],
  },
  {
    id: 'upgrade_tactician',
    name: 'Tactician',
    description: 'Switching weapons grants temporary crit.',
    weight: 4,
    tags: ['crit', 'flow'],
  },
];

export const SYNERGIES: SynergyDefinition[] = [
  {
    id: 'synergy_storm',
    name: 'Storm Conductor',
    description: 'Shock and chain effects loop for bigger arcs.',
    requirements: [{ tag: 'shock' }, { tag: 'chain' }],
    bonusTags: ['pulse'],
  },
  {
    id: 'synergy_shatter',
    name: 'Frozen Fracture',
    description: 'Cryo stacks explode on crits.',
    requirements: [{ tag: 'cryo' }, { tag: 'shatter' }, { tag: 'crit' }],
    bonusTags: ['aoe'],
  },
  {
    id: 'synergy_bleed',
    name: 'Bleed Line',
    description: 'Piercing shots refresh bleed stacks.',
    requirements: [{ tag: 'bleed' }, { tag: 'pierce' }],
    bonusTags: ['dot'],
  },
  {
    id: 'synergy_overheat',
    name: 'Overclock Loop',
    description: 'Overheat builds faster but reloads vent it.',
    requirements: [{ tag: 'overheat' }, { tag: 'reload' }],
    bonusTags: ['flow'],
  },
  {
    id: 'synergy_orbit',
    name: 'Orbital Battery',
    description: 'Orbs orbit longer and trigger pulses.',
    requirements: [{ tag: 'orb' }, { tag: 'orbit' }],
    bonusTags: ['pulse'],
  },
  {
    id: 'synergy_drone',
    name: 'Drone Swarm',
    description: 'Drone counts scale with summon effects.',
    requirements: [{ tag: 'drone' }, { tag: 'summon' }],
    bonusTags: ['support'],
  },
  {
    id: 'synergy_volatile',
    name: 'Volatile Payload',
    description: 'Explosions chain into shrapnel bursts.',
    requirements: [{ tag: 'explosive' }, { tag: 'volatile' }],
    bonusTags: ['aoe'],
  },
  {
    id: 'synergy_molten',
    name: 'Molten Core',
    description: 'Burn stacks feed explosive radius.',
    requirements: [{ tag: 'burn' }, { tag: 'dot' }],
    bonusTags: ['aoe'],
  },
  {
    id: 'synergy_rail',
    name: 'Rail Focus',
    description: 'Rail weapons gain crit scaling.',
    requirements: [{ tag: 'rail' }, { tag: 'precision' }],
    bonusTags: ['crit'],
  },
  {
    id: 'synergy_scatter',
    name: 'Scatterstorm',
    description: 'Close-range sprays generate extra pellets.',
    requirements: [{ tag: 'scatter' }, { tag: 'spray' }],
    bonusTags: ['close'],
  },
  {
    id: 'synergy_echo',
    name: 'Echo Chamber',
    description: 'Beam impacts echo for bonus pulses.',
    requirements: [{ tag: 'beam' }, { tag: 'echo' }],
    bonusTags: ['pulse'],
  },
  {
    id: 'synergy_corrosive',
    name: 'Corrosion Cascade',
    description: 'Corrosive dots chain across targets.',
    requirements: [{ tag: 'corrosive' }, { tag: 'dot' }, { tag: 'chain' }],
    bonusTags: ['status'],
  },
  {
    id: 'synergy_magnet',
    name: 'Magnetic Ricochet',
    description: 'Ricochets bend toward magnetized targets.',
    requirements: [{ tag: 'ricochet' }, { tag: 'magnet' }],
    bonusTags: ['utility'],
  },
  {
    id: 'synergy_shrapnel',
    name: 'Shrapnel Bloom',
    description: 'Explosions send piercing shards.',
    requirements: [{ tag: 'explosive' }, { tag: 'pierce' }],
    bonusTags: ['aoe'],
  },
  {
    id: 'synergy_barrier',
    name: 'Barrier Hacker',
    description: 'Shock effects amplify barriers.',
    requirements: [{ tag: 'barrier' }, { tag: 'shock' }],
    bonusTags: ['shield'],
  },
  {
    id: 'synergy_reactor',
    name: 'Pocket Reactor',
    description: 'Energy weapons ramp with flow stacks.',
    requirements: [{ tag: 'energy' }, { tag: 'flow' }],
    bonusTags: ['stacking'],
  },
  {
    id: 'synergy_hunter',
    name: 'Hunter Killer',
    description: 'Crits spike harder on precision hits.',
    requirements: [{ tag: 'crit' }, { tag: 'precision' }, { tag: 'spike' }],
    bonusTags: ['long'],
  },
  {
    id: 'synergy_chill',
    name: 'Chill Orbit',
    description: 'Orbiting cryo shots shatter on impact.',
    requirements: [{ tag: 'cryo' }, { tag: 'orbit' }],
    bonusTags: ['shatter'],
  },
  {
    id: 'synergy_support',
    name: 'Field Surgeon',
    description: 'Support actions trigger healing waves.',
    requirements: [{ tag: 'support' }, { tag: 'healing' }],
    bonusTags: ['shield'],
  },
  {
    id: 'synergy_velocity',
    name: 'Velocity Stack',
    description: 'Light weapons stack speed for burst windows.',
    requirements: [{ tag: 'light' }, { tag: 'burst' }],
    bonusTags: ['flow'],
  },
];
