import { describe, expect, it } from 'vitest';
import { makeTestRoom } from './testUtils';
import { GameState, EnemyState, ProjectileState } from '../rooms/schema/GameState';

describe('Projectiles', () => {
  it('cannon splash damages multiple enemies', () => {
    const room = makeTestRoom();
    room.state = new GameState();
    const e1 = new EnemyState();
    e1.id = 'e1';
    e1.kind = 'chaser';
    e1.health = 20;
    e1.position.x = 0;
    e1.position.y = 0;
    const e2 = new EnemyState();
    e2.id = 'e2';
    e2.kind = 'runner';
    e2.health = 20;
    e2.position.x = 8;
    e2.position.y = 0;
    room.state.enemies.push(e1, e2);
    const p = new ProjectileState();
    p.id = 'p1';
    p.kind = 'cannon';
    p.owner = 'player';
    p.damage = 20;
    p.position.x = 0;
    p.position.y = 0;
    p.velocity.x = 0;
    p.velocity.y = 0;
    p.ttl = 1;
    room.state.projectiles.push(p);
    room.updateProjectiles(0.05);
    expect(room.state.enemies.length).toBeLessThan(2);
  });

  it('rocket explosion triggers on ttl expiry', () => {
    const room = makeTestRoom();
    room.state = new GameState();
    const enemy = new EnemyState();
    enemy.id = 'e1';
    enemy.kind = 'chaser';
    enemy.health = 30;
    enemy.position.x = 0;
    enemy.position.y = 0;
    room.state.enemies.push(enemy);
    const p = new ProjectileState();
    p.id = 'p1';
    p.kind = 'rocket';
    p.owner = 'player';
    p.damage = 36;
    p.position.x = 0;
    p.position.y = 0;
    p.velocity.x = 0;
    p.velocity.y = 0;
    p.ttl = 0.01;
    room.state.projectiles.push(p);
    room.updateProjectiles(0.05);
    expect(room.state.projectiles.length).toBe(0);
    expect(room.state.enemies.length).toBe(0);
  });

  it('enemy projectile damages ship', () => {
    const room = makeTestRoom();
    room.state = new GameState();
    room.state.ship.health = 100;
    const p = new ProjectileState();
    p.id = 'p1';
    p.kind = 'spit';
    p.owner = 'enemy';
    p.damage = 8;
    p.position.x = 0;
    p.position.y = 0;
    p.velocity.x = 0;
    p.velocity.y = 0;
    p.ttl = 1;
    room.state.projectiles.push(p);
    room.updateProjectiles(0.05);
    expect(room.state.ship.health).toBeLessThan(100);
  });

  it('tracks gunner hit and kill stats', () => {
    const room = makeTestRoom();
    room.state = new GameState();
    const enemy = new EnemyState();
    enemy.id = 'e1';
    enemy.kind = 'chaser';
    enemy.health = 4;
    enemy.position.x = 0;
    enemy.position.y = 0;
    room.state.enemies.push(enemy);
    const p = new ProjectileState();
    p.id = 'p1';
    p.kind = 'mg';
    p.owner = 'player';
    p.damage = 6;
    p.position.x = 0;
    p.position.y = 0;
    p.velocity.x = 0;
    p.velocity.y = 0;
    p.ttl = 1;
    room.state.projectiles.push(p);
    room.updateProjectiles(0.05);
    expect(room.seatStats.gunner.hits).toBeGreaterThanOrEqual(1);
    expect(room.seatStats.gunner.kills).toBeGreaterThanOrEqual(1);
  });

  it('applies exposed damage multiplier', () => {
    const room = makeTestRoom();
    room.state = new GameState();
    room.simulationTime = 10000;
    const enemy = new EnemyState();
    enemy.id = 'e1';
    enemy.kind = 'chaser';
    enemy.health = 11;
    enemy.exposedUntil = 12;
    enemy.position.x = 0;
    enemy.position.y = 0;
    room.state.enemies.push(enemy);
    const p = new ProjectileState();
    p.id = 'p1';
    p.kind = 'mg';
    p.owner = 'player';
    p.damage = 10;
    p.position.x = 0;
    p.position.y = 0;
    p.velocity.x = 0;
    p.velocity.y = 0;
    p.ttl = 1;
    room.state.projectiles.push(p);
    room.updateProjectiles(0.05);
    expect(room.state.enemies.length).toBe(0);
  });

  it('triggers volatile explosion on kill', () => {
    const room = makeTestRoom();
    room.state = new GameState();
    room.simulationTime = 10000;
    const volatileEnemy = new EnemyState();
    volatileEnemy.id = 'e1';
    volatileEnemy.kind = 'chaser';
    volatileEnemy.health = 6;
    volatileEnemy.volatileUntil = 12;
    volatileEnemy.position.x = 0;
    volatileEnemy.position.y = 0;
    const nearby = new EnemyState();
    nearby.id = 'e2';
    nearby.kind = 'runner';
    nearby.health = 20;
    nearby.position.x = 6;
    nearby.position.y = 0;
    room.state.enemies.push(volatileEnemy, nearby);
    const p = new ProjectileState();
    p.id = 'p1';
    p.kind = 'mg';
    p.owner = 'player';
    p.damage = 8;
    p.position.x = 0;
    p.position.y = 0;
    p.velocity.x = 0;
    p.velocity.y = 0;
    p.ttl = 1;
    room.state.projectiles.push(p);
    room.updateProjectiles(0.05);
    const remaining = room.state.enemies.find((enemy) => enemy.id === 'e2');
    expect(remaining?.health ?? 0).toBeLessThan(20);
  });
});
